import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  ink: "#1A241F",
  inkSoft: "#2C3630",
  muted: "#4A5750",
  mutedLight: "#7A8A80",
  accent: "#55705F",
  accentGreen: "#8FBF9F",
  border: "#D8D3C4",
  borderLight: "#E4E0D6",
  bg: "#FAF9F6",
  bgGreen: "#EEF4EF",
  warnBg: "#FAF0E4",
  warnBorder: "#E8C89A",
  warnText: "#7A4A12",
  okBg: "#E6F2EA",
  okText: "#2D6A4F",
  badBg: "#FDECEA",
  badText: "#B42318",
  warnBadgeBg: "#FAF0E4",
  warnBadgeText: "#9A5B1A",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: colors.inkSoft,
    lineHeight: 1.45,
  },
  coverPage: {
    paddingTop: 120,
    paddingBottom: 40,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
  },
  coverBrand: {
    fontSize: 9,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: colors.accent,
    marginBottom: 36,
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: colors.ink,
    marginBottom: 16,
  },
  coverBusiness: {
    fontSize: 16,
    fontWeight: 700,
    color: colors.inkSoft,
    marginBottom: 8,
  },
  coverMeta: {
    fontSize: 10,
    color: colors.muted,
    marginBottom: 4,
  },
  coverDate: {
    fontSize: 10,
    color: colors.mutedLight,
    marginTop: 12,
  },
  coverRule: {
    borderBottomWidth: 2,
    borderBottomColor: colors.ink,
    marginTop: 48,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: colors.ink,
    marginBottom: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  subhead: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.inkSoft,
    marginTop: 12,
    marginBottom: 6,
  },
  lead: {
    fontSize: 10,
    color: colors.muted,
    marginBottom: 12,
  },
  body: {
    fontSize: 10,
    color: colors.inkSoft,
    marginBottom: 8,
  },
  muted: {
    fontSize: 9,
    color: colors.mutedLight,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  metricCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    padding: 10,
    backgroundColor: colors.bg,
  },
  metricCardPrimary: {
    backgroundColor: colors.bgGreen,
    borderColor: colors.accentGreen,
  },
  metricValue: {
    fontSize: 16,
    fontWeight: 700,
    color: colors.ink,
  },
  metricLabel: {
    fontSize: 8,
    color: colors.accent,
    marginTop: 4,
  },
  calloutWarn: {
    backgroundColor: colors.warnBg,
    borderWidth: 1,
    borderColor: colors.warnBorder,
    borderRadius: 4,
    padding: 10,
    marginBottom: 14,
  },
  calloutWarnText: {
    fontSize: 9,
    color: colors.warnText,
  },
  presenceCard: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  presenceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  presenceLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.ink,
  },
  badge: {
    fontSize: 8,
    fontWeight: 700,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 3,
  },
  badgeOk: { backgroundColor: colors.okBg, color: colors.okText },
  badgeWarn: { backgroundColor: colors.warnBadgeBg, color: colors.warnBadgeText },
  badgeBad: { backgroundColor: colors.badBg, color: colors.badText },
  badgeNeutral: { backgroundColor: "#F0F0F0", color: "#555555" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableRow: {
    flexDirection: "row",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.borderLight,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  colPrompt: { width: "42%" },
  colMentioned: { width: "14%" },
  colModels: { width: "44%" },
  cellText: { fontSize: 9, color: colors.inkSoft },
  cellBold: { fontSize: 9, fontWeight: 700, color: colors.ink },
  responseBlock: { marginBottom: 12 },
  responsePrompt: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.ink,
    marginBottom: 6,
  },
  responseItem: {
    marginBottom: 8,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: colors.border,
  },
  responseMeta: {
    fontSize: 8,
    color: colors.accent,
    marginBottom: 3,
  },
  responseText: {
    fontSize: 9,
    color: colors.inkSoft,
  },
  responseSources: {
    fontSize: 8,
    color: colors.mutedLight,
    marginTop: 3,
  },
  planItem: { marginBottom: 12 },
  planTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.ink,
    marginBottom: 4,
  },
  generatedBox: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 4,
    padding: 8,
    marginTop: 4,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: colors.mutedLight,
    marginBottom: 2,
  },
  bulletItem: {
    fontSize: 9,
    color: colors.inkSoft,
    marginBottom: 4,
    paddingLeft: 8,
  },
});
